export const SAVE_DETAILS = 'SAVE_DETAILS';
export const FETCH_IMAGE_START="FETCH_IMAGE_START";
export const FETCH_IMAGE_ERROR="FETCH_IMAGE_ERROR";
export const FETCH_IMAGE_RECEIVED="FETCH_IMAGE_RECEIVED";